#
# Copyright (c) 2026 Fujitsu Limited. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
dev.langchain4j.cdi.plugin.demo-model.class=dev.langchain4j.model.googleai.GoogleAiGeminiChatModel
dev.langchain4j.cdi.plugin.demo-model.config.api-key=${GOOGLE_API_KEY}
dev.langchain4j.cdi.plugin.demo-model.config.model-name=gemini-2.5-flash-lite
dev.langchain4j.cdi.plugin.demo-model.config.baseUrl=http://localhost:99999
dev.langchain4j.cdi.plugin.demo-model.config.max-retries=0
dev.langchain4j.cdi.plugin.demo-model.config.timeout=PT1S

