package com.fujitsu.demo;

import dev.langchain4j.cdi.spi.RegisterSimpleAgent;
import dev.langchain4j.service.UserMessage;
import dev.langchain4j.service.V;

@RegisterSimpleAgent(
    name = "problemSolverAgent",
    description = "Solves the arithmetic problem generated by the previous agent",
    outputKey = "answer",
    chatModelName = "#default",
    toolProviderName = "calculatorMcpToolProvider")
public interface ProblemSolverAgent {

  @UserMessage("""
      Solve the following arithmetic problem by calling exactly one of the
      provided MCP calculator tools: add, sub, mul, or div. You must use a tool
      for the calculation; do not calculate the result yourself.
      Problem: {{problem}}

      Show the original problem, the calculation, and the final answer.
      """)
  String solve(@V("problem") String problem);
}