#
# Copyright (c) 2026 Fujitsu Limited. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

### model settings
dev.langchain4j.cdi.plugin.demo-model.class=dev.langchain4j.model.googleai.GoogleAiGeminiChatModel
dev.langchain4j.cdi.plugin.demo-model.config.api-key=${GOOGLE_API_KEY}
dev.langchain4j.cdi.plugin.demo-model.config.model-name=gemini-2.5-flash-lite

### listener settings
dev.langchain4j.cdi.plugin.demo-model.config.listeners=dev.langchain4j.cdi.telemetry.MetricsChatModelListener
#dev.langchain4j.cdi.plugin.demo-model.config.listeners=dev.langchain4j.cdi.telemetry.SpanChatModelListener

### otel settings
otel.sdk.disabled=false
otel.service.name=JAKARTA-DEMO
otel.metrics.exporter=otlp
otel.metric.export.interval=5000
otel.traces.exporter=none
otel.logs.exporter=none

