#
# Copyright (c) 2026 Fujitsu Limited. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

dev.langchain4j.cdi.plugin.demo-model.class=dev.langchain4j.model.googleai.GoogleAiGeminiChatModel
dev.langchain4j.cdi.plugin.demo-model.config.api-key=${GOOGLE_API_KEY}
dev.langchain4j.cdi.plugin.demo-model.config.model-name=gemini-3.5-flash-lite
dev.langchain4j.cdi.plugin.demo-model.config.return-thinking=true
dev.langchain4j.cdi.plugin.demo-model.config.send-thinking=true
#dev.langchain4j.cdi.plugin.demo-model.config.log-requests-and-responses=true


calculator.mcp.url=http://localhost:9090/mcp
calculator.mcp.token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuY29tIiwic3ViIjoiZHVrZS11c2VyLTAwMSIsImlhdCI6MTc4OTcxODk0MCwiZXhwIjoxNzg5NzY5MDA1LCJ1cG4iOiJkdWtlQGV4YW1wbGUuY29tIiwianRpIjoiYTUzYmRlMzQtN2I3Mi00OTBiLTg5YjQtYzNjYjMxNWUwNDIzIiwiZ3JvdXBzIjpbImRldmVsb3BlcnMiLCJhZG1pbiJdLCJjdXN0b20tZGV0YWlsIjoiY3VzdG9tLWRhdGEifQ.ck0n7yusyHBXfCEDR-x5oecybjuMgb0Syi5L2p058IEUS8EheeTMymtCM1jYm3sJe9dBDHmLvpqxPY1yt0imUte2WZapuYo-s_-VtLab4iIaibqH8Ij0gs7RPTzXt_lawFBnwFzTeKxt9L1tWNzPZ0O3NHK7v-wY8RcDKKCEm-w-gc90V7lcXAMmK_tfJ-dns8ZApaWz-lEdcIU6noLCCwgkrVsezAx1D_HmUGQlmmksTh9exXXZMMXUXbyO5UXxYMQVEbCQhtxpVPUCQyCohMFeK5rYmGBd08WDF8NquDW673WXxfk9p6jM4k4HsedWQkzVCrAZ2aTGPuFwEUkSFQ

